### ISSUE TITLE
[bug]: The operation couldn't be completed. (NSURLErrorDomain error -1011.)

### ISSUE THREAD

**Issue by luk-dushaj** [MythicApp/Mythic#192]
### Describe the bug

For context, I updated Mythic and it took me through the setup process again.
Then when I got to the “Install Mythic Engine” screen, I clicked to install and got “Onboarding has failed to complete.” with that NSURLErrorDomain error.
Yes I know there has been a similar error in the past but I haven’t experienced this error on the last version.
https://github.com/MythicApp/Mythic/issues/172

### How to reproduce

1. Update Mythic
2. Go through the setup process and click to install Mythic engine
3. Then the error appears

### Mac & App Information

Model: MacBook Pro M2 16gb - OS: macOS Sequoia 15.3 - App Version: 0.4.4

### Logs

```bash

```

### Before submitting

- [x] I've made research efforts
- [x] I've searched for existing issues

**Comment by sakkarose** [comment]
Same thing, I tried reinstall but no luck. Unlucky this happened on a friday night.

**Comment by holohermet** [comment]
Exactly the same thing

**Comment by holohermet** [comment]
Looks like guys have a problem with 7.7 Engine nightly artifact :)
Weird, but the artifact itself is available, but nightly said that Github returns 404 error.
Just download it directly from the artifact, extract it in Downloads directory and do this in terminal:

```bash
cp -R ~/Downloads/Engine ~/Library/Application Support/Mythic
```

Then restart a Mythic.

**Comment by whitedieci** [comment]
> Looks like guys have a problem with 7.7 Engine nightly artifact :) Weird, but the artifact itself is available, but nightly said that Github returns 404 error.
> 
> Just download it directly from the artifact: https://github.com/MythicApp/Engine/suites/30670345622/artifacts/2164305429
> 
> Extract it in Downloads directory and do this in terminal:
> 
> cp -R ~/Downloads/Engine ~/Library/Application Support/Mythic
> Then restart a Mythic.
> 
> ## P.S. It's just a temporary solution
> 
> P.P.S Looks like this way there will be an issue with allowing of running execution files :)

so do you recommend this method or not?

**Comment by holohermet** [comment]
Hm, sorry - but no, because it was installed manually it was not associated with Mythic application and all wine executables are restrticted to run by Apple...

**Comment by vapidinfinity** [comment]
Please await a fix -- the github artifact that this was pointing to has expired, and there were some problems rebuilding.
The problem has nothing to do with the Mythic update.

If all goes well, a fix should be live in roughly 3 hours.

**Comment by vapidinfinity** [comment]
fixed!

**Comment by etroverde** [comment]
Even if solved still have the problem. Error NSURLErrorDomain -1011
