### ISSUE TITLE
[BUG] Application crashes on boot up after updating to v0.2.0

### ISSUE THREAD

**Issue by Frostzone123** [MythicApp/Mythic#86]
The apps seems to crash almost immediately after booting up after I updated to version 0.2.0. 

My Device: Macbook M2 Pro

**Comment by The-Warden-Jori** [comment]
I am also having the instant crashing issue now too, here are the logs


-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mythic [1216]
Path:                  /Volumes/VOLUME/*/Mythic.app/Contents/MacOS/Mythic
Identifier:            xyz.blackxfiied.Mythic
Version:               0.2.0-alpha (2754)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-06-13 13:52:46.2952 -0400
OS Version:            macOS 14.3 (23D56)
Report Version:        12
Anonymous UUID:        8296E367-48B4-C1EB-C80D-59C62A08D1A8


Time Awake Since Boot: 170 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1216]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4371578864
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104910000-104aa0000    [ 1600K] r-x/r-x SM=COW  .../MacOS/Mythic

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x189f55420 objc_msgSend + 32
1   Foundation                    	       0x18b7445f0 protocol witness for static Equatable.== infix(_:_:) in conformance URL + 32
2   Mythic                        	       0x10493aa8c 0x104910000 + 174732
3   Mythic                        	       0x1049332a4 0x104910000 + 144036
4   AttributeGraph                	       0x1b6eb0440 AGDispatchEquatable + 24
5   AttributeGraph                	       0x1b6e9655c AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 1600
6   AttributeGraph                	       0x1b6e9691c AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 96
7   AttributeGraph                	       0x1b6e9601c AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 256
8   AttributeGraph                	       0x1b6e9691c AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 96
9   SwiftUI                       	       0x1b659ba5c 0x1b5039000 + 22424156
10  libswiftCore.dylib            	       0x199d59348 withUnsafePointer<A, B>(to:_:) + 28
11  SwiftUI                       	       0x1b659b814 0x1b5039000 + 22423572
12  SwiftUI                       	       0x1b5f931d4 0x1b5039000 + 16097748
13  libswiftCore.dylib            	       0x199d59348 withUnsafePointer<A, B>(to:_:) + 28
14  SwiftUI                       	       0x1b5f922e8 0x1b5039000 + 16093928
15  SwiftUI                       	       0x1b5f923b8 0x1b5039000 + 16094136
16  SwiftUI                       	       0x1b5f912bc 0x1b5039000 + 16089788
17  SwiftUI                       	       0x1b5f90984 0x1b5039000 + 16087428
18  SwiftUI                       	       0x1b5f909f0 0x1b5039000 + 16087536
19  AttributeGraph                	       0x1b6eb0440 AGDispatchEquatable + 24
20  AttributeGraph                	       0x1b6e9655c AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 1600
21  AttributeGraph                	       0x1b6e961cc AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 688
22  AttributeGraph                	       0x1b6e9691c AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int) + 96
23  AttributeGraph                	       0x1b6ea53fc AGGraphSetOutputValue + 268
24  SwiftUI                       	       0x1b684f32c 0x1b5039000 + 25256748
25  SwiftUI                       	       0x1b5e875f8 0x1b5039000 + 15001080
26  libswiftCore.dylib            	       0x199d59348 withUnsafePointer<A, B>(to:_:) + 28
27  SwiftUI                       	       0x1b5e857b4 0x1b5039000 + 14993332
28  SwiftUI                       	       0x1b5e875d8 0x1b5039000 + 15001048
29  SwiftUI                       	       0x1b5e83c58 0x1b5039000 + 14986328
30  SwiftUI                       	       0x1b5e83d3c 0x1b5039000 + 14986556
31  SwiftUI                       	       0x1b5e85620 0x1b5039000 + 14992928
32  SwiftUI                       	       0x1b5e875ac 0x1b5039000 + 15001004
33  libswiftCore.dylib            	       0x199d59348 withUnsafePointer<A, B>(to:_:) + 28
34  SwiftUI                       	       0x1b5e8554c 0x1b5039000 + 14992716
35  SwiftUI                       	       0x1b634b834 0x1b5039000 + 19998772
36  AttributeGraph                	       0x1b6e837a4 AG::Graph::UpdateStack::update() + 512
37  AttributeGraph                	       0x1b6e83fe0 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 424
38  AttributeGraph                	       0x1b6e92828 AG::Subgraph::update(unsigned int) + 848
39  SwiftUI                       	       0x1b6788f18 0x1b5039000 + 24444696
40  SwiftUI                       	       0x1b678a3fc 0x1b5039000 + 24450044
41  SwiftUI                       	       0x1b5e332a4 0x1b5039000 + 14656164
42  SwiftUI                       	       0x1b685fad4 0x1b5039000 + 25324244
43  SwiftUI                       	       0x1b685e330 0x1b5039000 + 25318192
44  SwiftUI                       	       0x1b5e2ba6c 0x1b5039000 + 14625388
45  SwiftUI                       	       0x1b678a3c4 0x1b5039000 + 24449988
46  SwiftUI                       	       0x1b678a2b0 0x1b5039000 + 24449712
47  SwiftUI                       	       0x1b60db12c 0x1b5039000 + 17441068
48  SwiftUI                       	       0x1b56b2420 0x1b5039000 + 6788128
49  SwiftUI                       	       0x1b56b238c 0x1b5039000 + 6787980
50  SwiftUI                       	       0x1b56b24b4 0x1b5039000 + 6788276
51  CoreFoundation                	       0x18a3fed80 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
52  CoreFoundation                	       0x18a3fec6c __CFRunLoopDoObservers + 532
53  CoreFoundation                	       0x18a3fd988 CFRunLoopRunSpecific + 684
54  HIToolbox                     	       0x1949c6448 RunCurrentEventLoopInMode + 292
55  HIToolbox                     	       0x1949c6284 ReceiveNextEventCommon + 648
56  HIToolbox                     	       0x1949c5fdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
57  AppKit                        	       0x18dbdced0 _DPSNextEvent + 660
58  AppKit                        	       0x18e3c7eec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
59  AppKit                        	       0x18de0f1e8 -[NSApplication _doModalLoop:peek:] + 216
60  AppKit                        	       0x18de0e0f0 __35-[NSApplication runModalForWindow:]_block_invoke_2 + 56
61  AppKit                        	       0x18de0e09c __35-[NSApplication runModalForWindow:]_block_invoke + 108
62  AppKit                        	       0x18de0d968 _NSTryRunModal + 100
63  AppKit                        	       0x18de0d828 -[NSApplication runModalForWindow:] + 292
64  AppKit                        	       0x18e00a090 __19-[NSAlert runModal]_block_invoke_2 + 120
65  AppKit                        	       0x18e009ffc __19-[NSAlert runModal]_block_invoke + 108
66  AppKit                        	       0x18de0d968 _NSTryRunModal + 100
67  AppKit                        	       0x18de7dae0 -[NSAlert runModal] + 140
68  Mythic                        	       0x104948214 0x104910000 + 229908
69  Mythic                        	       0x1049494b8 0x104910000 + 234680
70  SwiftUI                       	       0x1b6724818 0x1b5039000 + 24033304
71  SwiftUI                       	       0x1b6724a9c 0x1b5039000 + 24033948
72  CoreFoundation                	       0x18a3f4500 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
73  CoreFoundation                	       0x18a48862c ___CFXRegistrationPost_block_invoke + 88
74  CoreFoundation                	       0x18a488574 _CFXRegistrationPost + 440
75  CoreFoundation                	       0x18a3c316c _CFXNotificationPost + 764
76  Foundation                    	       0x18b4b7f50 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
77  AppKit                        	       0x18dbe48ac -[NSApplication _postDidFinishNotification] + 284
78  AppKit                        	       0x18dbe465c -[NSApplication _sendFinishLaunchingNotification] + 172
79  AppKit                        	       0x18dbe2ba4 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 504
80  AppKit                        	       0x18dbe27a0 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 492
81  Foundation                    	       0x18b4e0374 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 316
82  Foundation                    	       0x18b4e0168 _NSAppleEventManagerGenericHandler + 80
83  AE                            	       0x19136adc0 0x19135f000 + 48576
84  AE                            	       0x19136a6e8 0x19135f000 + 46824
85  AE                            	       0x191363cf8 aeProcessAppleEvent + 488
86  HIToolbox                     	       0x1949d62d4 AEProcessAppleEvent + 68
87  AppKit                        	       0x18dbdd1dc _DPSNextEvent + 1440
88  AppKit                        	       0x18e3c7eec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
89  AppKit                        	       0x18dbd037c -[NSApplication run] + 476
90  AppKit                        	       0x18dba7640 NSApplicationMain + 880
91  SwiftUI                       	       0x1b5113004 0x1b5039000 + 892932
92  SwiftUI                       	       0x1b59a25ec 0x1b5039000 + 9868780
93  SwiftUI                       	       0x1b5de9a18 0x1b5039000 + 14354968
94  Mythic                        	       0x1049e7108 0x104910000 + 880904
95  dyld                          	       0x189fa10e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x18a31ce28 start_wqthread + 0

Thread 2::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	       0x18a2e1874 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18a2f3cf0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18a2ea4b0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x18a2e1bf8 mach_msg + 24
4   CoreFoundation                	       0x18a3ffb84 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18a3fe44c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18a3fd93c CFRunLoopRunSpecific + 608
7   Foundation                    	       0x18b509998 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   AppKit                        	       0x18e010b4c -[NSAnimation _runBlocking] + 324
9   libdispatch.dylib             	       0x18a16ecb8 _dispatch_call_block_and_release + 32
10  libdispatch.dylib             	       0x18a170910 _dispatch_client_callout + 20
11  libdispatch.dylib             	       0x18a1823cc _dispatch_root_queue_drain + 864
12  libdispatch.dylib             	       0x18a182a04 _dispatch_worker_thread2 + 156
13  libsystem_pthread.dylib       	       0x18a31e0d8 _pthread_wqthread + 228
14  libsystem_pthread.dylib       	       0x18a31ce30 start_wqthread + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x18a31ce28 start_wqthread + 0

Thread 4:
0   libsystem_kernel.dylib        	       0x18a2e8b34 __posix_spawn + 8
1   libsystem_kernel.dylib        	       0x18a2e8acc posix_spawn + 500
2   Foundation                    	       0x18b576d3c -[NSConcreteTask launchWithDictionary:error:] + 2900
3   Mythic                        	       0x10498944c 0x104910000 + 496716
4   Mythic                        	       0x10498e3e5 0x104910000 + 517093
5   Mythic                        	       0x104919d25 0x104910000 + 40229
6   Mythic                        	       0x10493a525 0x104910000 + 173349
7   Mythic                        	       0x10491a291 0x104910000 + 41617
8   libswift_Concurrency.dylib    	       0x22b585bf1 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 5:
0   libsystem_kernel.dylib        	       0x18a2e8b34 __posix_spawn + 8
1   libsystem_kernel.dylib        	       0x18a2e8acc posix_spawn + 500
2   Foundation                    	       0x18b576d3c -[NSConcreteTask launchWithDictionary:error:] + 2900
3   Mythic                        	       0x10498944c 0x104910000 + 496716
4   Mythic                        	       0x10498e3e5 0x104910000 + 517093
5   Mythic                        	       0x104919d25 0x104910000 + 40229
6   Mythic                        	       0x10493a525 0x104910000 + 173349
7   Mythic                        	       0x10491a291 0x104910000 + 41617
8   libswift_Concurrency.dylib    	       0x22b585bf1 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18a2e1874 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18a2f3cf0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18a2ea4b0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x18a2e1bf8 mach_msg + 24
4   CoreFoundation                	       0x18a3ffb84 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18a3fe44c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18a3fd93c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x18dd06160 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x18a322034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18a31ce3c thread_start + 8

Thread 7:
0   libsystem_pthread.dylib       	       0x18a31ce28 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x18a31ce28 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x18a31ce28 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0xd65f03c0910103ff   x1: 0x00000001d9670599   x2: 0xd65f03c0910103ff   x3: 0x0000000149033590
    x4: 0x0000000149033598   x5: 0x000000018b7445d0   x6: 0x00000001b68faa3c   x7: 0x0000600000084840
    x8: 0x00000001e218a000   x9: 0x00000000d65f03c0  x10: 0x8f9d0001e0beb2c0  x11: 0xffffffffffffffac
   x12: 0xffffffffffffffac  x13: 0x0000000000000001  x14: 0x0000000104ab7f98  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x00000001e2224448  x18: 0x0000000000000000  x19: 0x00000001049d960c
   x20: 0x00000001e21ab910  x21: 0x0000000000000000  x22: 0x00000001049d960c  x23: 0x00000001e21ab910
   x24: 0x000000016b4eb100  x25: 0x00000001e2683220  x26: 0x000000016b4eb110  x27: 0x000000016b4eb0d0
   x28: 0x000000016b4eb0e0   fp: 0x000000016b4eb0c0   lr: 0x000000018b7445f0
    sp: 0x000000016b4eb0c0   pc: 0x0000000189f55420 cpsr: 0x60001000
   far: 0x0000000000000010  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x104ffc000 -        0x105007fff libobjc-trampolines.dylib (*) <39d1d8d0-6996-3bd4-8ce9-39512bb65c82> /usr/lib/libobjc-trampolines.dylib
       0x10502c000 -        0x10506ffff org.sparkle-project.Sparkle (2.6.3) <914decbd-a6a8-366a-99ff-0316837f8814> /Volumes/VOLUME/*/Mythic.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x104910000 -        0x104a9ffff xyz.blackxfiied.Mythic (0.2.0-alpha) <d2929cda-53a5-3e1d-8110-ef52fa95e4a8> /Volumes/VOLUME/*/Mythic.app/Contents/MacOS/Mythic
       0x189f4c000 -        0x189f9afe0 libobjc.A.dylib (*) <375f98a8-1d18-3da7-92a3-b7964847b03a> /usr/lib/libobjc.A.dylib
       0x18b4af000 -        0x18c0f6fff com.apple.Foundation (6.9) <343d22b2-6c9a-3290-aa4d-18be70ab68ad> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1b6e79000 -        0x1b6ebcfff com.apple.AttributeGraph (5.0.77) <9188ca30-7fe7-37ac-ae5e-32843dbff9e2> /System/Library/PrivateFrameworks/AttributeGraph.framework/Versions/A/AttributeGraph
       0x1b5039000 -        0x1b6e78fff com.apple.SwiftUI (5.3.3) <397e2054-e98d-3d1e-bf74-4fd8e5fb0f49> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x199bf1000 -        0x19a131fff libswiftCore.dylib (*) <7eba7ef0-57d2-3155-b45d-1a4d40a732f3> /usr/lib/swift/libswiftCore.dylib
       0x18a382000 -        0x18a859fff com.apple.CoreFoundation (6.9) <6030a572-b731-3f46-b3a0-2598fbb98c9a> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x194996000 -        0x194c55fff com.apple.HIToolbox (2.1.1) <db8a8b63-7bfb-384b-b0a9-c124675fbb39> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x18dba3000 -        0x18eecefff com.apple.AppKit (6.9) <873e5da0-bc01-399b-bf60-4066922d6a17> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x19135f000 -        0x1913d2ff7 com.apple.AE (944) <1b2c4fa1-33cf-324a-84d8-134e07056155> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
       0x189f9b000 -        0x18a02f387 dyld (*) <50746901-db0e-39a0-b391-baaa6b82ad0f> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18a31b000 -        0x18a327ff3 libsystem_pthread.dylib (*) <449bbad3-f7ef-371d-9a59-fd4ffa78289b> /usr/lib/system/libsystem_pthread.dylib
       0x18a2e0000 -        0x18a31afff libsystem_kernel.dylib (*) <a7228b5d-53c7-3fe9-84e4-2a8c04dcf051> /usr/lib/system/libsystem_kernel.dylib
       0x18a16d000 -        0x18a1b3fff libdispatch.dylib (*) <5aa1649c-ef1d-39f7-a66c-4c5d2e53c474> /usr/lib/system/libdispatch.dylib
       0x22b53c000 -        0x22b59aff3 libswift_Concurrency.dylib (*) <2eb0df2b-7b1d-3d6d-90f1-9f8cc621b18f> /usr/lib/swift/libswift_Concurrency.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)
Writable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                           416K        8 
ColorSync                          608K       29 
CoreAnimation                     1424K       77 
CoreGraphics                        48K        3 
CoreServices                       128K        1 
CoreUI image data                 2864K       22 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.6G       60 
MALLOC guard page                  288K       18 
SQLite page cache                  256K        2 
STACK GUARD                       56.2M       10 
Stack                             12.8M       10 
VM_ALLOCATE                        448K       11 
__AUTH                            1962K      341 
__AUTH_CONST                      29.1M      547 
__CTF                               824        1 
__DATA                            14.2M      537 
__DATA_CONST                      27.8M      555 
__DATA_DIRTY                      1801K      201 
__FONT_DATA                          4K        1 
__LINKEDIT                       892.3M        4 
__OBJC_RO                         71.2M        1 
__OBJC_RW                         2171K        1 
__TEXT                           634.8M      574 
dyld private memory                272K        2 
mapped file                      192.9M       46 
shared memory                      896K       16 
===========                     =======  ======= 
TOTAL                              3.5G     3084 



-----------
Full Report
-----------

{"app_name":"Mythic","timestamp":"2024-06-13 13:52:46.00 -0400","app_version":"0.2.0-alpha","slice_uuid":"d2929cda-53a5-3e1d-8110-ef52fa95e4a8","build_version":"2754","platform":1,"bundleID":"xyz.blackxfiied.Mythic","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.3 (23D56)","roots_installed":0,"name":"Mythic","incident_id":"F156AD56-6094-4F69-8B82-FAF2A55C15C6"}
{
  "uptime" : 170,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "coalitionID" : 900,
  "osVersion" : {
    "train" : "macOS 14.3",
    "build" : "23D56",
    "releaseType" : "User"
  },
  "captureTime" : "2024-06-13 13:52:46.2952 -0400",
  "codeSigningMonitor" : 1,
  "incident" : "F156AD56-6094-4F69-8B82-FAF2A55C15C6",
  "pid" : 1216,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-06-13 13:52:45.4749 -0400",
  "procStartAbsTime" : 4074271750,
  "procExitAbsTime" : 4093918026,
  "procName" : "Mythic",
  "procPath" : "\/Volumes\/VOLUME\/*\/Mythic.app\/Contents\/MacOS\/Mythic",
  "bundleInfo" : {"CFBundleShortVersionString":"0.2.0-alpha","CFBundleVersion":"2754","CFBundleIdentifier":"xyz.blackxfiied.Mythic"},
  "storeInfo" : {"deviceIdentifierForVendor":"602C6E11-4179-5F6E-8295-120F0AF1BFB5","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "xyz.blackxfiied.Mythic",
  "crashReporterKey" : "8296E367-48B4-C1EB-C80D-59C62A08D1A8",
  "codeSigningID" : "xyz.blackxfiied.Mythic",
  "codeSigningTeamID" : "67ZBY275P8",
  "codeSigningFlags" : 1644245777,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"HyAD1R8gA9UfAADxzQMAVA4AQPnQzX2S6gMAqipc7fJQGcHa7wMQqg==","atPC":"CgpA+Uv9cNNKvUCSLAALCk0RDIuxJf+oPwEB64EAAFRKAQHKSgEQyg=="},
  "sip" : "enabled",
  "vmRegionInfo" : "0x10 is not in any region.  Bytes before following region: 4371578864\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104910000-104aa0000    [ 1600K] r-x\/r-x SM=COW  ...\/MacOS\/Mythic",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000010","rawCodes":[1,16],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000010"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":1216},
  "vmregioninfo" : "0x10 is not in any region.  Bytes before following region: 4371578864\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104910000-104aa0000    [ 1600K] r-x\/r-x SM=COW  ...\/MacOS\/Mythic",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":11729,"threadState":{"x":[{"value":15447069372505457663},{"value":7942374809,"objc-selector":"isEqual:"},{"value":15447069372505457663},{"value":5519914384},{"value":5519914392},{"value":6634620368,"symbolLocation":0,"symbol":"protocol witness for static Equatable.== infix(_:_:) in conformance URL"},{"value":7357835836},{"value":105553116809280},{"value":8088231936},{"value":3596551104},{"value":10348427526832829120},{"value":18446744073709551532},{"value":18446744073709551532},{"value":1},{"value":4373315480},{"value":0},{"value":0},{"value":8088863816},{"value":0},{"value":4372403724},{"value":8088369424,"symbolLocation":0,"symbol":"type metadata for URL"},{"value":0},{"value":4372403724},{"value":8088369424,"symbolLocation":0,"symbol":"type metadata for URL"},{"value":6095286528},{"value":8093446688,"symbolLocation":0,"symbol":"value witness table for Builtin.UnknownObject"},{"value":6095286544},{"value":6095286480},{"value":6095286496}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6634620400},"cpsr":{"value":1610616832},"fp":{"value":6095286464},"sp":{"value":6095286464},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6609523744,"matchesCrashFrame":1},"far":{"value":16}},"queue":"com.apple.main-thread","frames":[{"imageOffset":37920,"symbol":"objc_msgSend","symbolLocation":32,"imageIndex":3},{"imageOffset":2708976,"symbol":"protocol witness for static Equatable.== infix(_:_:) in conformance URL","symbolLocation":32,"imageIndex":4},{"imageOffset":174732,"imageIndex":2},{"imageOffset":144036,"imageIndex":2},{"imageOffset":226368,"symbol":"AGDispatchEquatable","symbolLocation":24,"imageIndex":5},{"imageOffset":120156,"symbol":"AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":1600,"imageIndex":5},{"imageOffset":121116,"symbol":"AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":96,"imageIndex":5},{"imageOffset":118812,"symbol":"AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":256,"imageIndex":5},{"imageOffset":121116,"symbol":"AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":96,"imageIndex":5},{"imageOffset":22424156,"imageIndex":6},{"imageOffset":1475400,"symbol":"withUnsafePointer<A, B>(to:_:)","symbolLocation":28,"imageIndex":7},{"imageOffset":22423572,"imageIndex":6},{"imageOffset":16097748,"imageIndex":6},{"imageOffset":1475400,"symbol":"withUnsafePointer<A, B>(to:_:)","symbolLocation":28,"imageIndex":7},{"imageOffset":16093928,"imageIndex":6},{"imageOffset":16094136,"imageIndex":6},{"imageOffset":16089788,"imageIndex":6},{"imageOffset":16087428,"imageIndex":6},{"imageOffset":16087536,"imageIndex":6},{"imageOffset":226368,"symbol":"AGDispatchEquatable","symbolLocation":24,"imageIndex":5},{"imageOffset":120156,"symbol":"AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":1600,"imageIndex":5},{"imageOffset":119244,"symbol":"AG::LayoutDescriptor::Compare::operator()(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":688,"imageIndex":5},{"imageOffset":121116,"symbol":"AG::LayoutDescriptor::compare(unsigned char const*, unsigned char const*, unsigned char const*, unsigned long, unsigned int)","symbolLocation":96,"imageIndex":5},{"imageOffset":181244,"symbol":"AGGraphSetOutputValue","symbolLocation":268,"imageIndex":5},{"imageOffset":25256748,"imageIndex":6},{"imageOffset":15001080,"imageIndex":6},{"imageOffset":1475400,"symbol":"withUnsafePointer<A, B>(to:_:)","symbolLocation":28,"imageIndex":7},{"imageOffset":14993332,"imageIndex":6},{"imageOffset":15001048,"imageIndex":6},{"imageOffset":14986328,"imageIndex":6},{"imageOffset":14986556,"imageIndex":6},{"imageOffset":14992928,"imageIndex":6},{"imageOffset":15001004,"imageIndex":6},{"imageOffset":1475400,"symbol":"withUnsafePointer<A, B>(to:_:)","symbolLocation":28,"imageIndex":7},{"imageOffset":14992716,"imageIndex":6},{"imageOffset":19998772,"imageIndex":6},{"imageOffset":42916,"symbol":"AG::Graph::UpdateStack::update()","symbolLocation":512,"imageIndex":5},{"imageOffset":45024,"symbol":"AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int)","symbolLocation":424,"imageIndex":5},{"imageOffset":104488,"symbol":"AG::Subgraph::update(unsigned int)","symbolLocation":848,"imageIndex":5},{"imageOffset":24444696,"imageIndex":6},{"imageOffset":24450044,"imageIndex":6},{"imageOffset":14656164,"imageIndex":6},{"imageOffset":25324244,"imageIndex":6},{"imageOffset":25318192,"imageIndex":6},{"imageOffset":14625388,"imageIndex":6},{"imageOffset":24449988,"imageIndex":6},{"imageOffset":24449712,"imageIndex":6},{"imageOffset":17441068,"imageIndex":6},{"imageOffset":6788128,"imageIndex":6},{"imageOffset":6787980,"imageIndex":6},{"imageOffset":6788276,"imageIndex":6},{"imageOffset":511360,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__","symbolLocation":36,"imageIndex":8},{"imageOffset":511084,"symbol":"__CFRunLoopDoObservers","symbolLocation":532,"imageIndex":8},{"imageOffset":506248,"symbol":"CFRunLoopRunSpecific","symbolLocation":684,"imageIndex":8},{"imageOffset":197704,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":9},{"imageOffset":197252,"symbol":"ReceiveNextEventCommon","symbolLocation":648,"imageIndex":9},{"imageOffset":196572,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":9},{"imageOffset":237264,"symbol":"_DPSNextEvent","symbolLocation":660,"imageIndex":10},{"imageOffset":8539884,"symbol":"-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":10},{"imageOffset":2540008,"symbol":"-[NSApplication _doModalLoop:peek:]","symbolLocation":216,"imageIndex":10},{"imageOffset":2535664,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke_2","symbolLocation":56,"imageIndex":10},{"imageOffset":2535580,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke","symbolLocation":108,"imageIndex":10},{"imageOffset":2533736,"symbol":"_NSTryRunModal","symbolLocation":100,"imageIndex":10},{"imageOffset":2533416,"symbol":"-[NSApplication runModalForWindow:]","symbolLocation":292,"imageIndex":10},{"imageOffset":4616336,"symbol":"__19-[NSAlert runModal]_block_invoke_2","symbolLocation":120,"imageIndex":10},{"imageOffset":4616188,"symbol":"__19-[NSAlert runModal]_block_invoke","symbolLocation":108,"imageIndex":10},{"imageOffset":2533736,"symbol":"_NSTryRunModal","symbolLocation":100,"imageIndex":10},{"imageOffset":2992864,"symbol":"-[NSAlert runModal]","symbolLocation":140,"imageIndex":10},{"imageOffset":229908,"imageIndex":2},{"imageOffset":234680,"imageIndex":2},{"imageOffset":24033304,"imageIndex":6},{"imageOffset":24033948,"imageIndex":6},{"imageOffset":468224,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":148,"imageIndex":8},{"imageOffset":1074732,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":8},{"imageOffset":1074548,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":8},{"imageOffset":266604,"symbol":"_CFXNotificationPost","symbolLocation":764,"imageIndex":8},{"imageOffset":36688,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":88,"imageIndex":4},{"imageOffset":268460,"symbol":"-[NSApplication _postDidFinishNotification]","symbolLocation":284,"imageIndex":10},{"imageOffset":267868,"symbol":"-[NSApplication _sendFinishLaunchingNotification]","symbolLocation":172,"imageIndex":10},{"imageOffset":261028,"symbol":"-[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:]","symbolLocation":504,"imageIndex":10},{"imageOffset":260000,"symbol":"-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:]","symbolLocation":492,"imageIndex":10},{"imageOffset":201588,"symbol":"-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:]","symbolLocation":316,"imageIndex":4},{"imageOffset":201064,"symbol":"_NSAppleEventManagerGenericHandler","symbolLocation":80,"imageIndex":4},{"imageOffset":48576,"imageIndex":11},{"imageOffset":46824,"imageIndex":11},{"imageOffset":19704,"symbol":"aeProcessAppleEvent","symbolLocation":488,"imageIndex":11},{"imageOffset":262868,"symbol":"AEProcessAppleEvent","symbolLocation":68,"imageIndex":9},{"imageOffset":238044,"symbol":"_DPSNextEvent","symbolLocation":1440,"imageIndex":10},{"imageOffset":8539884,"symbol":"-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":10},{"imageOffset":185212,"symbol":"-[NSApplication run]","symbolLocation":476,"imageIndex":10},{"imageOffset":17984,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":10},{"imageOffset":892932,"imageIndex":6},{"imageOffset":9868780,"imageIndex":6},{"imageOffset":14354968,"imageIndex":6},{"imageOffset":880904,"imageIndex":2},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":12}]},{"id":11739,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6095859712},{"value":5123},{"value":6095323136},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6095859712},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613487144},"far":{"value":0}}},{"id":11740,"threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":216616675573760},{"value":0},{"value":216616675573760},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":50435},{"value":0},{"value":1},{"value":50435},{"value":1701771},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8217098288},{"value":0},{"value":4294967295},{"value":2},{"value":216616675573760},{"value":0},{"value":216616675573760},{"value":6096428808},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6613318896},"cpsr":{"value":4096},"fp":{"value":6096428656},"sp":{"value":6096428576},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613244020},"far":{"value":0}},"queue":"com.apple.root.user-interactive-qos","frames":[{"imageOffset":6260,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":15},{"imageOffset":81136,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":15},{"imageOffset":42160,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":15},{"imageOffset":7160,"symbol":"mach_msg","symbolLocation":24,"imageIndex":15},{"imageOffset":514948,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":8},{"imageOffset":509004,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":8},{"imageOffset":506172,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":8},{"imageOffset":371096,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":4},{"imageOffset":4643660,"symbol":"-[NSAnimation _runBlocking]","symbolLocation":324,"imageIndex":10},{"imageOffset":7352,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":16},{"imageOffset":14608,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":16},{"imageOffset":86988,"symbol":"_dispatch_root_queue_drain","symbolLocation":864,"imageIndex":16},{"imageOffset":88580,"symbol":"_dispatch_worker_thread2","symbolLocation":156,"imageIndex":16},{"imageOffset":12504,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":14},{"imageOffset":7728,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":14}]},{"id":11748,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6097006592},{"value":20483},{"value":6096470016},{"value":0},{"value":409603},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6097006592},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613487144},"far":{"value":0}}},{"id":11771,"frames":[{"imageOffset":35636,"symbol":"__posix_spawn","symbolLocation":8,"imageIndex":15},{"imageOffset":35532,"symbol":"posix_spawn","symbolLocation":500,"imageIndex":15},{"imageOffset":818492,"symbol":"-[NSConcreteTask launchWithDictionary:error:]","symbolLocation":2900,"imageIndex":4},{"imageOffset":496716,"imageIndex":2},{"imageOffset":517093,"imageIndex":2},{"imageOffset":40229,"imageIndex":2},{"imageOffset":173349,"imageIndex":2},{"imageOffset":41617,"imageIndex":2},{"imageOffset":302065,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":17}],"threadState":{"x":[{"value":0},{"value":0},{"value":6097576976},{"value":6097577504},{"value":105553131504560},{"value":105553131504560},{"value":0},{"value":0},{"value":0},{"value":3128},{"value":1040},{"value":0},{"value":2147483652},{"value":2149580804},{"value":4294967295},{"value":2147483648},{"value":244},{"value":8088864224},{"value":0},{"value":105553131504560},{"value":6097577504},{"value":5522002944},{"value":105553162633744},{"value":6097576976},{"value":8065614608,"symbolLocation":0,"symbol":"errno"},{"value":9},{"value":6097580256},{"value":105553131504560},{"value":4294967295}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6613273292},"cpsr":{"value":4096},"fp":{"value":6097577200},"sp":{"value":6097576976},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613273396},"far":{"value":0}}},{"id":11773,"frames":[{"imageOffset":35636,"symbol":"__posix_spawn","symbolLocation":8,"imageIndex":15},{"imageOffset":35532,"symbol":"posix_spawn","symbolLocation":500,"imageIndex":15},{"imageOffset":818492,"symbol":"-[NSConcreteTask launchWithDictionary:error:]","symbolLocation":2900,"imageIndex":4},{"imageOffset":496716,"imageIndex":2},{"imageOffset":517093,"imageIndex":2},{"imageOffset":40229,"imageIndex":2},{"imageOffset":173349,"imageIndex":2},{"imageOffset":41617,"imageIndex":2},{"imageOffset":302065,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":17}],"threadState":{"x":[{"value":0},{"value":0},{"value":6098150416},{"value":6098150944},{"value":105553131685408},{"value":105553131685408},{"value":0},{"value":0},{"value":0},{"value":3128},{"value":1040},{"value":0},{"value":2147483776},{"value":2147483792},{"value":2147483647},{"value":2147483776},{"value":244},{"value":8088864224},{"value":0},{"value":105553131685408},{"value":6098150944},{"value":5511708672},{"value":105553162458480},{"value":6098150416},{"value":8065614608,"symbolLocation":0,"symbol":"errno"},{"value":9},{"value":6098153696},{"value":105553131685408},{"value":4294967295}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6613273292},"cpsr":{"value":4096},"fp":{"value":6098150640},"sp":{"value":6098150416},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613273396},"far":{"value":0}}},{"id":11824,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":219915210457088},{"value":0},{"value":219915210457088},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":51203},{"value":0},{"value":1},{"value":51203},{"value":1501883},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8217098288},{"value":0},{"value":4294967295},{"value":2},{"value":219915210457088},{"value":0},{"value":219915210457088},{"value":6099296360},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6613318896},"cpsr":{"value":4096},"fp":{"value":6099296208},"sp":{"value":6099296128},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613244020},"far":{"value":0}},"frames":[{"imageOffset":6260,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":15},{"imageOffset":81136,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":15},{"imageOffset":42160,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":15},{"imageOffset":7160,"symbol":"mach_msg","symbolLocation":24,"imageIndex":15},{"imageOffset":514948,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":8},{"imageOffset":509004,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":8},{"imageOffset":506172,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":8},{"imageOffset":1454432,"symbol":"_NSEventThread","symbolLocation":144,"imageIndex":10},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":11826,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6098726912},{"value":66055},{"value":6098190336},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6098726912},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6613487144},"far":{"value":0}}},{"id":11827,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6099873792},{"value":0},{"value":6099337216},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6099873792},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6613487144},"far":{"value":0}}},{"id":11828,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6100447232},{"value":0},{"value":6099910656},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6100447232},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6613487144},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4378836992,
    "size" : 49152,
    "uuid" : "39d1d8d0-6996-3bd4-8ce9-39512bb65c82",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4379033600,
    "CFBundleShortVersionString" : "2.6.3",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "914decbd-a6a8-366a-99ff-0316837f8814",
    "path" : "\/Volumes\/VOLUME\/*\/Mythic.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2039"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4371578880,
    "CFBundleShortVersionString" : "0.2.0-alpha",
    "CFBundleIdentifier" : "xyz.blackxfiied.Mythic",
    "size" : 1638400,
    "uuid" : "d2929cda-53a5-3e1d-8110-ef52fa95e4a8",
    "path" : "\/Volumes\/VOLUME\/*\/Mythic.app\/Contents\/MacOS\/Mythic",
    "name" : "Mythic",
    "CFBundleVersion" : "2754"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6609485824,
    "size" : 323553,
    "uuid" : "375f98a8-1d18-3da7-92a3-b7964847b03a",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6631911424,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 12877824,
    "uuid" : "343d22b2-6c9a-3290-aa4d-18be70ab68ad",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "2303"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7363596288,
    "CFBundleShortVersionString" : "5.0.77",
    "CFBundleIdentifier" : "com.apple.AttributeGraph",
    "size" : 278528,
    "uuid" : "9188ca30-7fe7-37ac-ae5e-32843dbff9e2",
    "path" : "\/System\/Library\/PrivateFrameworks\/AttributeGraph.framework\/Versions\/A\/AttributeGraph",
    "name" : "AttributeGraph",
    "CFBundleVersion" : "5.0.77"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7331876864,
    "CFBundleShortVersionString" : "5.3.3",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 31719424,
    "uuid" : "397e2054-e98d-3d1e-bf74-4fd8e5fb0f49",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.3.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6874402816,
    "size" : 5509120,
    "uuid" : "7eba7ef0-57d2-3155-b45d-1a4d40a732f3",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6613901312,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "6030a572-b731-3f46-b3a0-2598fbb98c9a",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2303"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6788046848,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 2883584,
    "uuid" : "db8a8b63-7bfb-384b-b0a9-c124675fbb39",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6672756736,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20103168,
    "uuid" : "873e5da0-bc01-399b-bf60-4066922d6a17",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.40.107"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6731198464,
    "CFBundleShortVersionString" : "944",
    "CFBundleIdentifier" : "com.apple.AE",
    "size" : 475128,
    "uuid" : "1b2c4fa1-33cf-324a-84d8-134e07056155",
    "path" : "\/System\/Library\/Frameworks\/CoreServices.framework\/Versions\/A\/Frameworks\/AE.framework\/Versions\/A\/AE",
    "name" : "AE",
    "CFBundleVersion" : "944"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6609809408,
    "size" : 607112,
    "uuid" : "50746901-db0e-39a0-b391-baaa6b82ad0f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6613479424,
    "size" : 53236,
    "uuid" : "449bbad3-f7ef-371d-9a59-fd4ffa78289b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6613237760,
    "size" : 241664,
    "uuid" : "a7228b5d-53c7-3fe9-84e4-2a8c04dcf051",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6611718144,
    "size" : 290816,
    "uuid" : "5aa1649c-ef1d-39f7-a66c-4c5d2e53c474",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9316843520,
    "size" : 389108,
    "uuid" : "2eb0df2b-7b1d-3d6d-90f1-9f8cc621b18f",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  }
],
  "sharedCache" : {
  "base" : 6609059840,
  "size" : 4065345536,
  "uuid" : "b81268a5-00ed-3883-b922-13118e8800fe"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                           416K        8 \nColorSync                          608K       29 \nCoreAnimation                     1424K       77 \nCoreGraphics                        48K        3 \nCoreServices                       128K        1 \nCoreUI image data                 2864K       22 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.6G       60 \nMALLOC guard page                  288K       18 \nSQLite page cache                  256K        2 \nSTACK GUARD                       56.2M       10 \nStack                             12.8M       10 \nVM_ALLOCATE                        448K       11 \n__AUTH                            1962K      341 \n__AUTH_CONST                      29.1M      547 \n__CTF                               824        1 \n__DATA                            14.2M      537 \n__DATA_CONST                      27.8M      555 \n__DATA_DIRTY                      1801K      201 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       892.3M        4 \n__OBJC_RO                         71.2M        1 \n__OBJC_RW                         2171K        1 \n__TEXT                           634.8M      574 \ndyld private memory                272K        2 \nmapped file                      192.9M       46 \nshared memory                      896K       16 \n===========                     =======  ======= \nTOTAL                              3.5G     3084 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "50c53edc08c20ce12f6f9c59da58155fce143684",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6410af69ed1e1e7ab93ed169",
      "factorPackIds" : {

      },
      "deploymentId" : 240000011
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3dff9c91-a8fb-424e-a656-c8d6e6037574",
      "experimentId" : "662152ede2d11d1408c4db33",
      "deploymentId" : 400000014
    }
  ]
}
}

Model: MacBookPro17,1, BootROM 10151.81.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Aug 26 2023 17:55:53 version 18.20.439.0.7.8.163 FWID 01-f9b9247b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by The-Warden-Jori** [comment]
I’m also having the instant crashing issue, at first I was able to open it normally, I updated normally and tried to input the C++ Runtime but now it just crashes instantly whenever I try to open it, I just posted the logs on GitHub above

**Comment by ChiliBeane** [comment]
Yeah same issue for me

**Comment by blackxfiied** [comment]
These logs normally don't provide too much info. So I can better assist you, please do the following:

1. If you can, head to the Console app installed on your mac.
2. In the search bar located toward the top right of Console, type `xyz.blackxfiied.Mythic`, and press return on your keyboard.
3. Now, in the search bar, there should be a dropdown that reads 'ANY'. click on this dropdown and select 'Subsystem', as shown.
<img width="345" alt="image" src="https://github.com/MythicApp/Mythic/assets/41133734/e3c57247-4ba9-45c1-8b3b-caa6469909c2">

4. In the top bar, you may click "Start", and replicate your issue in the Mythic app.
6. Now, you may return to console, and press ⌘ + A, followed by ⌘ + C to copy.
7. Paste your logs here.
8. You may now close the Console app.

**Comment by The-Warden-Jori** [comment]
This is all I have been able to get to show up using the steps you posted above, not sure if it is what you need but hope it helps…


error	19:48:31.349714-0400	Mythic	Unable to request notification authorization: <private>

**Comment by The-Warden-Jori** [comment]
So when trying to request the extended logs it says it it private and cannot be accessed? How do I make the logs not-private?

**Comment by zolars1966** [comment]
Same here. (Although, I don't think that the information about the model of my mac is necessary) on my MacBook Air M1 I have the same crash.

**Comment by blackxfiied** [comment]
So, the issue is with the binary of Mythic i've attached?
I can't replicate this issue, and I'm really in the dark as to what's happening

**Comment by theokougia** [comment]
Same exact issue, instant crash on boot after update

**Comment by trankhacvinh** [comment]
me too, instant crash when open the app after update. Holding control and right click to open it is no help

**Comment by asxrow66** [comment]
> Holding control and right click to open it is no help
This is only for bypassing it not being a trusted app to Apple.

**Comment by blackxfiied** [comment]
Found the issue.
Seems upgrading to Xcode 16 was a terrible idea.
Something unknown broke on Xcode that's making Mythic crash.
A fix will release shortly.

**Comment by ChiliBeane** [comment]
sounds good, im still on sonoma. i just removed the mythic engine and restarted onboarding and now everythings working perfectly!

**Comment by blackxfiied** [comment]
Fixed in 0.2.1.

**Comment by PeeJeeDR** [comment]
Thanks! I updated the version and updated the Mythic engine, it still crashed once after this, but when I restarted Mythic it seemed to work again.
